const GALLERY_ASSETS = [
    { name: 'IMG_1117.MOV', type: 'video', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_0444.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_0551.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_0558.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_0960.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_0962.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1064.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1102.JPG.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1131.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1132.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1133.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1138.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1143.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'Suriya.jpeg', type: 'image', label: 'Suriya', path: 'New folder of Bikers' },
    { name: 'Heartkannan.jpeg', type: 'image', label: 'Kannan', path: 'New folder of Bikers' },
    { name: 'Adnan Sait.jpeg', type: 'image', label: 'Adnan', path: 'New folder of Bikers' },
    { name: 'Pushpak Raj.jpeg', type: 'image', label: 'Pushbak', path: 'New folder of Bikers' },
    { name: 'Suresh.jpeg', type: 'image', label: 'Suresh', path: 'New folder of Bikers' },
    { name: 'Nobitaa.jpeg', type: 'image', label: 'Jeevan', path: 'New folder of Bikers' },
    { name: 'IMG_1312.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1858.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_1889.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_2036.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_2071.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_2073.jpg', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3224.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3225.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3226.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3227.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3228.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3229.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3230.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3231.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3232.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3233.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
    { name: 'IMG_3234.png', type: 'image', label: 'Expedition Log', path: 'assets/bikers' },
];
