plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\jskap\\OneDrive\\Desktop\\Community\\velocity-riders"
publishOrigin = "default"
base = "C:\\Users\\jskap\\OneDrive\\Desktop\\Community\\velocity-riders"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]