import os
import shutil
from PIL import Image
from pillow_heif import register_heif_opener

# Register HEIF opener with Pillow
register_heif_opener()

SRC_DIR = r"c:\Users\jskap\OneDrive\Desktop\Community\velocity-riders\Image of Bikers"
DEST_DIR = r"c:\Users\jskap\OneDrive\Desktop\Community\velocity-riders\assets\bikers"

def main():
    if not os.path.exists(DEST_DIR):
        os.makedirs(DEST_DIR)
        print(f"Created destination directory: {DEST_DIR}")

    files = os.listdir(SRC_DIR)
    processed_assets = []
    
    print(f"Found {len(files)} files in source directory.")
    
    for filename in sorted(files):
        file_path = os.path.join(SRC_DIR, filename)
        if os.path.isdir(file_path):
            continue
            
        lower_name = filename.lower()
        base_name, _ = os.path.splitext(filename)
        
        # Output file mapping
        dest_filename = None
        asset_type = "image"
        
        try:
            if lower_name.endswith(('.heic', '.heif')):
                # Convert HEIC/HEIF to JPEG
                dest_filename = f"{base_name}.jpg"
                dest_path = os.path.join(DEST_DIR, dest_filename)
                
                print(f"Converting {filename} -> {dest_filename}...")
                image = Image.open(file_path)
                # Keep color profile or convert to RGB
                if image.mode != 'RGB':
                    image = image.convert('RGB')
                image.save(dest_path, "JPEG", quality=85, optimize=True)
                processed_assets.append({"name": dest_filename, "type": "image"})
                
            elif lower_name.endswith(('.png', '.jpg', '.jpeg')):
                # Copy and optimize if image, or just copy
                ext = ".png" if lower_name.endswith('.png') else ".jpg"
                dest_filename = f"{base_name}{ext}"
                dest_path = os.path.join(DEST_DIR, dest_filename)
                
                print(f"Optimizing/Copying {filename} -> {dest_filename}...")
                image = Image.open(file_path)
                # Save optimized
                if lower_name.endswith('.png'):
                    image.save(dest_path, "PNG", optimize=True)
                else:
                    if image.mode != 'RGB':
                        image = image.convert('RGB')
                    image.save(dest_path, "JPEG", quality=85, optimize=True)
                processed_assets.append({"name": dest_filename, "type": "image"})
                
            elif lower_name.endswith(('.mov', '.mp4')):
                # Copy video file directly
                dest_filename = filename
                dest_path = os.path.join(DEST_DIR, dest_filename)
                print(f"Copying video {filename} -> {dest_filename}...")
                shutil.copy2(file_path, dest_path)
                processed_assets.append({"name": dest_filename, "type": "video"})
                
            else:
                print(f"Skipping unknown file format: {filename}")
                
        except Exception as e:
            print(f"Error processing {filename}: {e}")

    # Generate a JavaScript/JSON array file containing the list of processed assets
    js_output_path = os.path.join(r"c:\Users\jskap\OneDrive\Desktop\Community\velocity-riders\js", "gallery-data.js")
    with open(js_output_path, "w", encoding="utf-8") as f:
        f.write("// Automatically generated by convert_images.py\n")
        f.write("const GALLERY_ASSETS = [\n")
        for asset in processed_assets:
            f.write(f"    {{ name: '{asset['name']}', type: '{asset['type']}' }},\n")
        f.write("];\n")
    print(f"Successfully generated JS gallery data at: {js_output_path}")
    print(f"Processed total of {len(processed_assets)} assets.")

if __name__ == "__main__":
    main()
